### ISSUE TITLE
empty csv for extract example

### ISSUE THREAD

**Issue by alangi** [jpvantassel/swprocess#11]
There is no data in the extract_startandend.csv file in the extract example

**Comment by jpvantassel** [comment]
Hi @alangi,
Yes, this was intentional. You will also note that no demonstration data is provided. This example code is offered as a convenient utility for trimming miniSEED files, however the code makes several assumptions about how the miniSEED files are named/organized, as such it is not guaranteed to work for everyone. A future release with include a more general utility and associated examples. If you are looking for a tool to trim your miniSEED files, you can try using this utility, but if it does not work I would suggest using _obspy_ or a GUI-based tool such as _geopsy_.
