### ISSUE TITLE
Issue on "from_peakssuite"

### ISSUE THREAD

**Issue by seguj** [jpvantassel/swprocess#3]
Dear, Joseph 

Hello,
I'm Youngjun Jeon from Korea University in South, Korea.

First of all, thanks for your efforts on SWprocess.

I made two *.max files with array processing methods of rtbf and fk using Geopsy.
But from the line below, I receive an error, 'There already exists a member object with an identifier = 20220623113000.000000.'
'master_suite = swprocess.PeaksSuite.from_peakssuite(suites)'
I think it's because the two max files have an overlapping time-block (20220623113000.000000)
Is there any approach to avoid this, except using an individual time-window for each array method?

Best regards,
Youngjun Jeon

**Comment by jpvantassel** [comment]
Hi @seguj,

You have diagnosed the issue correctly, each `Peak` object must be associated with a unique identifier. When you load from a `.max` file that unique identifier is the start time of the associated time window. As you have processed your data twice, once with RTBF and once with FK and loaded the two associated `.max` files into two `PeakSuite` objects both contain the same identifiers and therefore cannot be merged into a single `PeakSuite` object.

In regards to a solution, I would suggest simply renaming the identifier so that each `Peak` in the `PeakSuite` will be unique. A clear and easy way to do this would be to loop across all the `Peak` objects in the `PeakSuite` and append an `"rtbf"` or `"fk"` to the end of each of the current identifiers to ensure they are unique. Once you have done this, you can merge the two `PeakSuites` together into a single `PeakSuite`.

All the best,
Joe

**Comment by seguj** [comment]
Dear, Joseph

Thanks for the fast reply!

As you recommended, I simply modified 'from_json' in 'PeaksSuite.'
I'm attaching that code for anyone facing the same issue.

########################
    def from_json(cls, fnames, label):

        if isinstance(fnames, str):
            fnames = [fnames]

        try:
            iter(fnames)
        except TypeError:
            fnames = [str(fnames)]

        dicts = []
        print(fnames)
        for fname in fnames):
            with open(fname, "r") as f:
                _data = json.load(f)
                _keys = [key for key in _data]
                _keys_label = [f'{key}.{label}' for key in _data]
                for _key, _key_label in zip(_keys, _keys_label):
                    _data[_key_label] = _data.pop(_key)
                dicts.append(_data)
                
                # dicts.append(json.load(f))
        return cls.from_dict(dicts)
########################

Best regards,
Youngjun
